export const empsData = [
  {
    empid: 101,
    empname: "Ravi Kumar",
    gender: "Male",
    designation: "Software Engineer",
    salary: 75000,
  },
  {
    empid: 102,
    empname: "Anjali Sharma",
    gender: "Female",
    designation: "HR Manager",
    salary: 68000,
  },
  {
    empid: 103,
    empname: "Vikram Singh",
    gender: "Male",
    designation: "Team Lead",
    salary: 92000,
  },
  {
    empid: 104,
    empname: "Neha Joshi",
    gender: "Female",
    designation: "UI/UX Designer",
    salary: 62000,
  },
  {
    empid: 105,
    empname: "Amitabh Desai",
    gender: "Male",
    designation: "Project Manager",
    salary: 105000,
  },
  {
    empid: 106,
    empname: "Pooja Mehta",
    gender: "Female",
    designation: "Data Analyst",
    salary: 67000,
  },
  {
    empid: 107,
    empname: "Suresh Iyer",
    gender: "Male",
    designation: "DevOps Engineer",
    salary: 83000,
  },
  {
    empid: 108,
    empname: "Kavya Reddy",
    gender: "Female",
    designation: "Marketing Executive",
    salary: 59000,
  },
  {
    empid: 109,
    empname: "Arjun Patel",
    gender: "Male",
    designation: "Business Analyst",
    salary: 74000,
  },
  {
    empid: 110,
    empname: "Divya Nair",
    gender: "Female",
    designation: "Content Strategist",
    salary: 61000,
  },

  {
    empid: 111,
    empname: "Rahul Verma",
    gender: "Male",
    designation: "Network Administrator",
    salary: 70000,
  },
  {
    empid: 112,
    empname: "Sneha Kapoor",
    gender: "Female",
    designation: "QA Engineer",
    salary: 65000,
  },
  {
    empid: 113,
    empname: "Manoj Bhatia",
    gender: "Male",
    designation: "Cloud Architect",
    salary: 115000,
  },
  {
    empid: 114,
    empname: "Priya Menon",
    gender: "Female",
    designation: "Product Manager",
    salary: 98000,
  },
  {
    empid: 115,
    empname: "Ashwin Rao",
    gender: "Male",
    designation: "Machine Learning Engineer",
    salary: 120000,
  },
  {
    empid: 116,
    empname: "Ishita Gupta",
    gender: "Female",
    designation: "Technical Writer",
    salary: 54000,
  },
  {
    empid: 117,
    empname: "Rajeev Nanda",
    gender: "Male",
    designation: "Security Analyst",
    salary: 88000,
  },
  {
    empid: 118,
    empname: "Meera Pillai",
    gender: "Female",
    designation: "Operations Manager",
    salary: 95000,
  },
  {
    empid: 119,
    empname: "Nikhil Jain",
    gender: "Male",
    designation: "Front-End Developer",
    salary: 72000,
  },
  {
    empid: 120,
    empname: "Tanvi Deshmukh",
    gender: "Female",
    designation: "Data Scientist",
    salary: 110000,
  },
];
